image: gcc

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

stages:
  - build
  - test

build_all:
  stage: build

  before_script:
    - apt update && apt -y install make

  script:
    - make re -C src/ EXE=../stash
    - make re -C src/ EXE=../stash-asan CFLAGS="-g3 -fsanitize=address"
    - make re -C src/ EXE=../stash-ubsan CFLAGS="-g3 -fsanitize=undefined"
    - make clean -C src/

  artifacts:
    paths:
      - stash
      - stash-asan
      - stash-ubsan

test_sanitize:
  stage: test

  script:
    - ./stash-asan bench 2>&1 | grep -A50 "ERROR:"
    - ./stash-ubsan bench 2>&1 | grep -A50 "runtime error:"

test_bench:
  stage: test

  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Bench:"'

  script:
    - sh utils/check_bench.sh "$CI_COMMIT_MESSAGE"
